### ISSUE TITLE
freezes on PopOS and Raspberry piOS

### ISSUE THREAD

**Issue by kety-folf** [pfndesign/fallout4-terminal-hack-reactnative#1]
the ARM64 and AMD64 deb files both freeze when running the program on linux and i did testing and its only the deb versions.
windows version works without lag

**Comment by pfndesign** [comment]
can you give me your system info?
neofetch
or 
uname -a

**Comment by kety-folf** [comment]
output of uname -a
```
Linux pop-os 5.15.23-76051523-generic #202202110435~1644952300~21.10~96763f1 SMP Tue Feb 15 19:52:40 U x86_64 x86_64 x86_64 GNU/Linux
```
CPU: Intel Celeron N3350 (2) @ 2.400GHz 
GPU: Intel HD Graphics 500
 Memory: 2436MiB / 3765MiB

**Comment by pfndesign** [comment]
Your Linux system cpu is not arm so arm64 not working makes sense
for popos because your cpu is intel amd64 not working make sense too because amd64 is for amd cpu
you can use "termlinkacess-1.0.6.x86_64.rpm" file
you can install it with "rpm -i termlinkacess-1.0.6.x86_64.rpm"
because my cpu is amd I can only build the .deb version for amd.

**Comment by kety-folf** [comment]
ah ok i thought AMD64 was still meant to be compatible with x64
